# Generated by Django 5.2.7 on 2025-12-19 10:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стоимость покупки"
            ),
        ),
    ]
