# Generated by Django 5.2.7 on 2025-12-19 14:34

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=2000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
