# Generated by Django 5.2.7 on 2025-11-18 13:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
    ]
